# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20aa0c9c74f7e221e2e0a692265a4378c121100eaf87a0633b11e911e4e065f82ae769507160fefc42f58b6bc125b073c9be6ff36ef494a3b502fdaeccb12c90

test:
  secret_key_base: 6552cf56272f2721888569eeb8a3f00c990df0b5c4a3cf793603552094a2917b67bd94492d8e01ed48a9a32f56ee79027247b097d0db452ca415506a490da556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
